### PR TITLE
Do not report sensitive variables in slack notifications

### PR DESCRIPTION
**Pull request by pdalpra**
This will, by default, don't even try to show sensitive build variables in the Slack notifications.
Necessary step for https://trello.com/c/bZa1avZS

### CODE REVIEW

**Comment by pdalpra** [comment]
cc @gbougeard

**Comment by gbougeard** [comment]
Where the sensitive build variables are setted in Jenkins?

**Comment by bjaglin** [comment]
LGTM, that won't hurt (I see you found the hidden params branch, maybe we should agree on a more visible strategy for such forks - the only convention we have now is to append a teadsX classifier to custom artifacts)

**Comment by pdalpra** [comment]
@gbougeard it happens here in the 'Mask passwords plugin' : https://github.com/jenkinsci/mask-passwords-plugin/blob/master/src/main/java/com/michelin/cio/hudson/plugins/maskpasswords/MaskPasswordsBuildWrapper.java#L170

@bjaglin It's almost treasure hunting :D but sure, we could for exemple have a dedicated `teads` branch or something like that :)

**Pull request merged**
